version: '3.8'

services:
  books-service:
    build: ./books-service
    ports:
      - "8081:8080"
    networks:
      - library-network

  loan-service:
    build: ./loan-service
    ports:
      - "8082:8080"
    networks:
      - library-network

  member-service:
    build: ./member-service
    ports:
      - "8083:8080"
    networks:
      - library-network

networks:
  library-network:
    driver: bridge